// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $index from "./routes/index.tsx";
import * as $projects_droppy_blocky_index from "./routes/projects/droppy-blocky/index.tsx";
import * as $projects_droppy_blocky_privacy_policy from "./routes/projects/droppy-blocky/privacy-policy.tsx";
import * as $projects_droppy_blocky_terms_and_conditions from "./routes/projects/droppy-blocky/terms-and-conditions.tsx";

import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/index.tsx": $index,
    "./routes/projects/droppy-blocky/index.tsx": $projects_droppy_blocky_index,
    "./routes/projects/droppy-blocky/privacy-policy.tsx":
      $projects_droppy_blocky_privacy_policy,
    "./routes/projects/droppy-blocky/terms-and-conditions.tsx":
      $projects_droppy_blocky_terms_and_conditions,
  },
  islands: {},
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
